# Generated by Django 6.1 on 2026-08-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='bi-cpu', max_length=50, verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(choices=[('inquiry', 'استفسار عام'), ('product', 'استفسار عن منتج'), ('order', 'طلب منتج'), ('technical', 'دعم فني'), ('partnership', 'شراكة'), ('other', 'أخرى')], max_length=50, verbose_name='الموضوع')),
                ('product_reference', models.CharField(blank=True, max_length=100, verbose_name='المنتج المطلوب')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('part_number', models.CharField(max_length=100, verbose_name='الرقم المرجعي / Part Number')),
                ('description', models.TextField(verbose_name='الوصف الكامل')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('pinout_image', models.ImageField(blank=True, upload_to='products/pinouts/', verbose_name='صورة Pinout')),
                ('datasheet', models.FileField(blank=True, upload_to='datasheets/', verbose_name='Datasheet PDF')),
                ('technical_info', models.TextField(blank=True, verbose_name='معلومات تقنية إضافية')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المواصفة')),
                ('value', models.CharField(max_length=255, verbose_name='القيمة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مواصفة',
                'verbose_name_plural': 'المواصفات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
