# Generated by Django 6.1 on 2026-08-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, choices=[('through-hole', 'Through-Hole'), ('smd', 'SMD / SMT'), ('dip', 'DIP'), ('sop', 'SOP / SOIC')], max_length=30, verbose_name='Package Type'),
        ),
    ]
