# Generated by Django 6.1 on 2026-08-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_icon_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Wilaya')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Wilaya Code')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Price (DZD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_type',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-cpu', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('full_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Product Unit Price (DZD)')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Delivery Price (DZD)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price (DZD)')),
                ('note', models.TextField(blank=True, verbose_name='Customer Note')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product', verbose_name='Product')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': 'Product Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
