# Generated by Django 6.1 on 2026-08-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_wilaya_remove_product_package_type_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='stock_deducted',
            field=models.BooleanField(default=False, editable=False, verbose_name='Stock Deducted'),
        ),
    ]
