# Generated by Django 6.1 on 2026-08-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productorder_stock_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('products_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Products Total (DZD)')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Delivery Price (DZD)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price (DZD)')),
                ('note', models.TextField(blank=True, verbose_name='Customer Note')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_orders', to='catalog.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Cart Order',
                'verbose_name_plural': 'Cart Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Product Unit Price (DZD)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Item Total Price (DZD)')),
                ('stock_deducted', models.BooleanField(default=False, editable=False, verbose_name='Stock Deducted')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cartorder', verbose_name='Cart Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_order_items', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Order Item',
                'verbose_name_plural': 'Cart Order Items',
                'ordering': ['id'],
            },
        ),
    ]
