# Generated by Django 6.1 on 2026-08-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cartorder_cartorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
