# Generated by Django 6.1 on 2026-08-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Specification Type',
                'verbose_name_plural': 'Specification Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='specification',
            name='specification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='catalog.specificationtype', verbose_name='Specification Type'),
        ),
    ]
