# Generated by Django 6.1 on 2026-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Wilaya Code'),
        ),
    ]
