# Generated by Django 6.1 on 2026-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinout_image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='products/pinouts/', verbose_name='Pinout Image'),
        ),
    ]
