# Generated by Django 6.1 on 2026-09-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='products/no image.png', upload_to='categories/', verbose_name='Image'),
        ),
    ]
