# Generated by Django 6.1 on 2026-09-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/no image.png', upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinout_image',
            field=models.ImageField(blank=True, default='products/no image.png', upload_to='products/pinouts/', verbose_name='Pinout Image'),
        ),
    ]
