# Generated by Django 6.1 on 2026-09-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_category_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Commune')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Commune Code')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Price (DZD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='catalog.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cartorder',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_orders', to='catalog.commune', verbose_name='Commune'),
        ),
    ]
