# Generated by Django 6.1 on 2026-09-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_commune_cartorder_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='code',
        ),
    ]
