# Generated by Django 6.1 on 2026-09-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_remove_commune_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='delivery_price',
        ),
    ]
