# Generated by Django 6.1 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_wilaya_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Phone'),
        ),
    ]
